### ISSUE TITLE
System Configuration Across Components

### ISSUE THREAD

**Issue by jpitts** [designforsf/brigade-matchmaker#37]
A design needs to be sketched out and prototyped. Requirements for a configuration system:

- configs are accessible: JSON stored in a top-level directory, not dotfiles
- protecting devs from making mistakes: a default JSON is checked in, all others gitignored
- segmented: define configurations targeting each component
- possibly using a standard node module, but not a requirement

**Comment by spease** [comment]
> configs are accessible: JSON stored in a top-level directory, not dotfiles

What does "config" mean - what information (name of service, port, etc)?

Ideally it would be nice if we could stick to one node version for the whole project from now on, but I kept most of the infrastructure in for having multiple node versions for different projects. So that could also be a per-component attribute.

Not in this config, and a separate thing, but there should be a way to store secrets - it sounds like Paul has run into this for his stuff.

> protecting devs from making mistakes: a default JSON is checked in, all others gitignored

Does this imply that the intention is to replace package.json? If so I would recommend against it - I think keeping a standard node structure is fine.

> segmented: define configurations targeting each component

See above - good to know what this is.

> possibly using a standard node module, but not a requirement

I'm not sure there's a clean way to address this.

There is a node module for using vagrant (https://www.npmjs.com/package/node-vagrant), but this would then require the developer to have node installed and set up correctly on their machine (in addition to having vagrant).

It looks like the JSON can be parsed by the Ruby Vagrantfile:
http://bitcubby.com/configuring-vagrant-json-ruby/

So I'd probably stick with that approach. I really like that the install approach is as easy as "vagrant up". I suppose it could be easier if there were a GUI.

**Comment by jpitts** [comment]
I definitely would not replace package.json!

By "config" I mean a data available to the application based on the deployment context. This may best be represented by a JSON file named after the NODE_ENV, e.g. etc/development.json or etc/staging.json, with only etc/example-config.json checked into the repo. A config would mainly contain credentials, but also domain name, etc. 

This config file can be used to generate nodejs environment variables, or perhaps it is loaded as an object accessible throughout the web app and even accessible via the REST API.

By "standard node module" I mean we can use some well-known module / approach for loading JSON config files.

**Comment by jpitts** [comment]
I added a very basic approach for this: https://github.com/designforsf/brigade-matchmaker/commit/fce18eec9e12efbedd1a84fc34c1ba68a0227e21

This proposed to use environment-named files in etc to configure all components. The components/common/lib/ConfigFile.js module is what would be used in the various nodejs services.

**Comment by jpitts** [comment]
Note: there are other changes in the commit to remove other uses of the term "config" in web app, which will reduce confusion.

**Comment by jpitts** [comment]
This was implemented.
