### ISSUE TITLE
Convert the taxonomy to yaml files, or perhaps a single yaml file.

### ISSUE THREAD

**Issue by rroueche** [designforsf/brigade-matchmaker#58]

**Comment by themightychris** [comment]
Hello! There's an iceboxed effort started between the laddr and brigadehub projects a couple summits ago to define a standard taxonomy format in YAML that different brigade tools could all share to build cross-mappable data across the network: https://github.com/Codeforamerica/civic-tech-taxonomy

The initial draft featured sorted YAML files, but since then my own thinking has evolved that we should just take advantage of git's already-sorted trees, and create a structure like

```
/topics/
   /crime.yaml
   /education.yaml
   /teaching -> education.yaml
/tech/
   ...
/skills
   ...
```

symlinks could be used to represent aliases. This would make it easiest to maintain a central repository and review/accept revisions via pull requests. UIs could be built later to make it easier for folks to submit revisions, and a CI script could be setup to automatically publish the database somewhere to multiple formats (json, csv, api) made convenient for consumption whenever the master branch changes (addressing #59 too)

**Comment by pauljickling** [comment]
Just making a quick note to indicate that the current plan is to target a TOML file to manage the taxonomy.

**Comment by themightychris** [comment]
@pauljickling awesome! I've been thinking the same thing, TOML is way less finicky for people to hand edit

**Comment by jpitts** [comment]
https://github.com/designforsf/brigade-matchmaker/issues/81

https://github.com/designforsf/brigade-matchmaker/issues/80
